name = "PointerStructs"
uuid = "0ac99047-f20c-4964-adcf-e848779dacfc"
authors = ["Julia Computing and contributors"]
version = "0.1.0"

[deps]
Static = "aedffcd0-7271-4cad-89d0-dc628f76c6d3"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"

[compat]
Static = "0.3"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
